version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL="mongodb+srv://ETicaretApp:Qazxsw123@eticaretapp.tkzxtey.mongodb.net/?retryWrites=true&w=majority&appName=ETicaretApp"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: